function out = imgs_in_docked_figures(imgs, names, varargin)
    out = gobjects(1, length(imgs));
    for i = 1:length(imgs)
        out(i) = figure( ...
            'WindowStyle', 'docked', ...
            'NumberTitle', 'off', ...
            'Units', 'normalized', ...
            'Position', [0, 0, 1, 1], ...
            'Name', names{i} ...
        );
        imshow(imgs{i}, 'InitialMagnification', 'fit');
    end
end