function out = docked_figure(varargin)
    out = figure( ...
        'WindowStyle', 'docked', ...
        'NumberTitle', 'off', ...
        'Units', 'normalized', ...
        'Position', [0, 0, 1, 1], ...
        varargin{:} ...
    );
end